### ISSUE TITLE
Run MacOS and Windows tests on Java 17

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#194]
Add two new `include` blocks to [the main YML pipeline](https://github.com/ascopes/java-compiler-testing/blob/main/.github/workflows/main.yml#L151) to enable CI to run on macos-12 on java 19 and windows-2022 on java 19.

**Comment by sohel-79** [comment]
```
include:
          - os-name: macos-12
            java-version: 11
          - os-name: windows-2022
            java-version: 11
          - os-name: macos-12
            java-version: 19
          - os-name: windows-2022
            java-version: 19
```

should it be like this ?
